"""initial schema

Revision ID: de5a43a55dc8
Revises: 
Create Date: 2026-09-04 09:57:16.713688
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'de5a43a55dc8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('service', sa.String(length=300), nullable=False),
    sa.Column('price_range', sa.String(length=120), nullable=False),
    sa.Column('target_customer', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('intelligence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('agent', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('token_usage', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_input_hash'), 'agent_runs', ['input_hash'], unique=False)
    op.create_index(op.f('ix_agent_runs_project_id'), 'agent_runs', ['project_id'], unique=False)
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('intent_score', sa.Float(), nullable=False),
    sa.Column('commercial_score', sa.Float(), nullable=False),
    sa.Column('opportunity_score', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('video_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('lead_count', sa.Integer(), nullable=False),
    sa.Column('s_count', sa.Integer(), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keywords_keyword'), 'keywords', ['keyword'], unique=False)
    op.create_index(op.f('ix_keywords_project_id'), 'keywords', ['project_id'], unique=False)
    op.create_index('ix_keywords_project_opportunity', 'keywords', ['project_id', 'opportunity_score'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('platform_user_id', sa.String(length=120), nullable=False),
    sa.Column('nickname', sa.String(length=120), nullable=False),
    sa.Column('profile_url', sa.String(length=500), nullable=False),
    sa.Column('lead_score', sa.Float(), nullable=False),
    sa.Column('lead_level', sa.String(length=2), nullable=False),
    sa.Column('intent_level', sa.String(length=20), nullable=False),
    sa.Column('need', sa.String(length=300), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('budget', sa.String(length=120), nullable=False),
    sa.Column('purchase_stage', sa.String(length=60), nullable=False),
    sa.Column('pain_point', sa.Text(), nullable=False),
    sa.Column('buying_signals', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('persona_advice', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_lead_level'), 'leads', ['lead_level'], unique=False)
    op.create_index(op.f('ix_leads_lead_score'), 'leads', ['lead_score'], unique=False)
    op.create_index(op.f('ix_leads_platform_user_id'), 'leads', ['platform_user_id'], unique=False)
    op.create_index(op.f('ix_leads_project_id'), 'leads', ['project_id'], unique=False)
    op.create_index('ix_leads_project_score', 'leads', ['project_id', 'lead_score'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_table('personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('identity', sa.String(length=200), nullable=False),
    sa.Column('experience', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('tone', sa.String(length=200), nullable=False),
    sa.Column('strengths', sa.Text(), nullable=False),
    sa.Column('forbidden_words', sa.Text(), nullable=False),
    sa.Column('sample_reply', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personas_project_id'), 'personas', ['project_id'], unique=False)
    op.create_table('scan_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('full', sa.Boolean(), nullable=False),
    sa.Column('current_step', sa.String(length=80), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_tasks_project_id'), 'scan_tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_scan_tasks_status'), 'scan_tasks', ['status'], unique=False)
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('platform_video_id', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('creator', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('cover', sa.String(length=500), nullable=False),
    sa.Column('publish_time', sa.DateTime(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('collects', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=200), nullable=False),
    sa.Column('opportunity_score', sa.Float(), nullable=False),
    sa.Column('industry_relevance_score', sa.Float(), nullable=False),
    sa.Column('commercial_relevance_score', sa.Float(), nullable=False),
    sa.Column('lead_opportunity_score', sa.Float(), nullable=False),
    sa.Column('level', sa.String(length=2), nullable=False),
    sa.Column('lead_density', sa.Float(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'platform', 'platform_video_id', name='uq_video_project_platform_id')
    )
    op.create_index(op.f('ix_videos_keyword'), 'videos', ['keyword'], unique=False)
    op.create_index(op.f('ix_videos_platform_video_id'), 'videos', ['platform_video_id'], unique=False)
    op.create_index(op.f('ix_videos_project_id'), 'videos', ['project_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('platform_comment_id', sa.String(length=120), nullable=False),
    sa.Column('platform_user_id', sa.String(length=120), nullable=False),
    sa.Column('nickname', sa.String(length=120), nullable=False),
    sa.Column('profile_url', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('parent_comment_id', sa.String(length=120), nullable=False),
    sa.Column('created_at_platform', sa.DateTime(), nullable=True),
    sa.Column('coverage_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'platform', 'platform_comment_id', name='uq_comment_project_platform_id')
    )
    op.create_index(op.f('ix_comments_content_hash'), 'comments', ['content_hash'], unique=False)
    op.create_index(op.f('ix_comments_platform_comment_id'), 'comments', ['platform_comment_id'], unique=False)
    op.create_index(op.f('ix_comments_platform_user_id'), 'comments', ['platform_user_id'], unique=False)
    op.create_index(op.f('ix_comments_project_id'), 'comments', ['project_id'], unique=False)
    op.create_index(op.f('ix_comments_video_id'), 'comments', ['video_id'], unique=False)
    op.create_table('lead_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_events_lead_id'), 'lead_events', ['lead_id'], unique=False)
    op.create_table('lead_sources',
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('lead_id', 'video_id')
    )
    op.create_table('task_checkpoints',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('last_keyword_id', sa.Integer(), nullable=False),
    sa.Column('last_video_id', sa.Integer(), nullable=False),
    sa.Column('last_comment_cursor', sa.String(length=200), nullable=False),
    sa.Column('processed_comment_ids', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['scan_tasks.id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('task_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['scan_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_events_event_type'), 'task_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_task_events_project_id'), 'task_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_task_events_task_id'), 'task_events', ['task_id'], unique=False)
    op.create_table('task_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['scan_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_table('task_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['scan_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_steps_task_id'), 'task_steps', ['task_id'], unique=False)
    op.create_table('lead_comments',
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('lead_id', 'comment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead_comments')
    op.drop_index(op.f('ix_task_steps_task_id'), table_name='task_steps')
    op.drop_table('task_steps')
    op.drop_table('task_reports')
    op.drop_index(op.f('ix_task_events_task_id'), table_name='task_events')
    op.drop_index(op.f('ix_task_events_project_id'), table_name='task_events')
    op.drop_index(op.f('ix_task_events_event_type'), table_name='task_events')
    op.drop_table('task_events')
    op.drop_table('task_checkpoints')
    op.drop_table('lead_sources')
    op.drop_index(op.f('ix_lead_events_lead_id'), table_name='lead_events')
    op.drop_table('lead_events')
    op.drop_index(op.f('ix_comments_video_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_project_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_platform_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_platform_comment_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_content_hash'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_videos_project_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_platform_video_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_keyword'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_scan_tasks_status'), table_name='scan_tasks')
    op.drop_index(op.f('ix_scan_tasks_project_id'), table_name='scan_tasks')
    op.drop_table('scan_tasks')
    op.drop_index(op.f('ix_personas_project_id'), table_name='personas')
    op.drop_table('personas')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index('ix_leads_project_score', table_name='leads')
    op.drop_index(op.f('ix_leads_project_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_platform_user_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_lead_score'), table_name='leads')
    op.drop_index(op.f('ix_leads_lead_level'), table_name='leads')
    op.drop_table('leads')
    op.drop_index('ix_keywords_project_opportunity', table_name='keywords')
    op.drop_index(op.f('ix_keywords_project_id'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_keyword'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_index(op.f('ix_agent_runs_project_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_input_hash'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_table('settings')
    op.drop_table('providers')
    op.drop_table('projects')
    # ### end Alembic commands ###
