import { useEffect, useState } from 'react'
import { Link, NavLink, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom'
import { Activity, ArrowUpRight, Bot, BrainCircuit, Check, ChevronRight, CircleHelp, Database, Gauge, LayoutDashboard, ListChecks, LucideIcon, MessageCircle, Radar, Search, Settings, Sparkles, Target, Video, Wifi, X } from 'lucide-react'
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from 'recharts'

const API = 'http://127.0.0.1:8688'
type AnyRecord = Record<string, any>

async function api(path: string, options?: RequestInit) {
  const response = await fetch(`${API}${path}`, { headers: { 'Content-Type': 'application/json' }, ...options })
  if (!response.ok) throw new Error((await response.json().catch(() => ({}))).detail || `请求失败 ${response.status}`)
  return response.json()
}

const navItems = [
  { to: '/', label: '总览', icon: LayoutDashboard }, { to: '/smart-mode', label: '智能截流', icon: Sparkles }, { to: '/keywords', label: '关键词雷达', icon: Radar }, { to: '/videos', label: '热门视频', icon: Video }, { to: '/leads', label: '潜客池', icon: Target }, { to: '/agents', label: '智能体', icon: Bot }, { to: '/tasks', label: '任务中心', icon: ListChecks }, { to: '/analytics', label: '数据分析', icon: Gauge }, { to: '/providers', label: '数据源', icon: Database }, { to: '/settings', label: '系统设置', icon: Settings },
]

function App() {
  const [projects, setProjects] = useState<AnyRecord[]>([])
  const [projectId, setProjectId] = useState<number>(1)
  useEffect(() => { api('/api/projects').then((items) => { setProjects(items); if (items[0]) setProjectId(items[0].id) }).catch(() => {}) }, [])
  return <div className="app-shell"><Sidebar projects={projects} projectId={projectId} setProjectId={setProjectId} /><main className="main-area"><Topbar projects={projects} projectId={projectId} /><Routes><Route path="/" element={<Dashboard projectId={projectId} />} /><Route path="/smart-mode" element={<SmartMode projectId={projectId} setProjectId={setProjectId} setProjects={setProjects} />} /><Route path="/keywords" element={<Keywords projectId={projectId} />} /><Route path="/videos" element={<Videos projectId={projectId} />} /><Route path="/leads" element={<Leads projectId={projectId} />} /><Route path="/leads/:leadId" element={<LeadDetail />} /><Route path="/agents" element={<Agents projectId={projectId} />} /><Route path="/tasks" element={<Tasks projectId={projectId} />} /><Route path="/analytics" element={<Analytics projectId={projectId} />} /><Route path="/providers" element={<Providers />} /><Route path="/settings" element={<SettingsPage />} /></Routes></main></div>
}

function Sidebar({ projects, projectId, setProjectId }: AnyRecord) {
  return <aside className="sidebar"><div className="brand"><div className="brand-mark"><Radar size={20} /></div><div><div className="brand-name">AI 截流雷达</div><div className="brand-sub">AI LEAD RADAR</div></div></div><div className="workspace-label">当前工作区</div><select className="project-select" value={projectId} onChange={(e) => setProjectId(Number(e.target.value))}>{projects.length ? projects.map((p: AnyRecord) => <option key={p.id} value={p.id}>{p.name}</option>) : <option value={1}>长沙装修</option>}</select><nav className="nav-list">{navItems.map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}><Icon size={17} strokeWidth={1.8} /><span>{label}</span>{label === '潜客池' && <span className="nav-count">50</span>}</NavLink>)}</nav><div className="sidebar-footer"><div className="provider-mini"><span className="pulse-dot" />Mock 数据模式<span className="tiny-arrow">↗</span></div><div className="user-row"><div className="avatar">L</div><div><div className="user-name">本地工作区</div><div className="user-role">个人版 · Windows</div></div><CircleHelp size={16} className="muted-icon" /></div></div></aside>
}

function Topbar({ projects, projectId }: AnyRecord) {
  const location = useLocation()
  const current = navItems.find((item) => item.to === location.pathname) || (location.pathname.startsWith('/leads/') ? { label: '潜客详情' } : { label: '总览' })
  return <header className="topbar"><div className="breadcrumbs"><span>工作区</span><ChevronRight size={14} /><span className="crumb-current">{current.label}</span></div><div className="top-actions"><div className="system-status"><span className="pulse-dot" />智能截流运行中</div><button className="icon-button"><Search size={17} /></button><button className="icon-button"><CircleHelp size={17} /></button><div className="top-avatar">L</div></div></header>
}

function PageTitle({ eyebrow, title, description, children }: AnyRecord) { return <div className="page-title"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{description && <p>{description}</p>}</div>{children && <div className="title-action">{children}</div>}</div> }
function StatCard({ label, value, helper, icon: Icon, accent }: AnyRecord) { return <div className="stat-card"><div className="stat-top"><span>{label}</span><div className={`stat-icon ${accent || ''}`}><Icon size={17} /></div></div><div className="stat-value">{value}</div><div className="stat-helper">{helper}</div></div> }
function Badge({ children, tone = 'neutral' }: AnyRecord) { return <span className={`badge ${tone}`}>{children}</span> }

function Dashboard({ projectId }: { projectId: number }) {
  const [data, setData] = useState<AnyRecord>({ stats: {}, events: [] }); const [liveEvents, setLiveEvents] = useState<AnyRecord[]>([])
  useEffect(() => { api(`/api/dashboard?project_id=${projectId}`).then(setData).catch(() => {}) }, [projectId])
  useEffect(() => { const source = new EventSource(`${API}/api/events/stream`); source.onmessage = (event) => { try { setLiveEvents((old) => [...old.slice(-19), JSON.parse(event.data)]) } catch {} }; return () => source.close() }, [])
  const stats = data.stats || {}; const events = [...(data.events || []), ...liveEvents].slice(-12)
  return <><PageTitle eyebrow="实时工作台" title="AI 截流雷达" description="系统正在替你理解行业、发现需求，并把真实的购买信号送到潜客池。"><div className="running-pill"><span className="pulse-dot" />智能截流运行中</div></PageTitle><div className="hero-strip"><div className="hero-copy"><div className="hero-kicker"><Sparkles size={15} /> INDUSTRY INTELLIGENCE</div><h2>{data.project?.location || '长沙'} · {data.project?.industry || '装修'} <span>行业雷达</span></h2><p>已连续运行 03:21:18　·　当前使用 Mock Provider，外部数据源可在设置中接入</p></div><Link to="/smart-mode" className="button primary">查看智能配置 <ArrowUpRight size={15} /></Link><div className="hero-orbit orbit-one" /><div className="hero-orbit orbit-two" /></div><div className="stats-grid"><StatCard label="今日扫描关键词" value={stats.keywords || 50} helper="↑ 12 个高机会词" icon={Radar} accent="violet" /><StatCard label="发现热门视频" value={stats.videos || 20} helper="S / A 级重点监控" icon={Video} accent="blue" /><StatCard label="分析公开评论" value={stats.comments || 300} helper="覆盖范围：未知" icon={MessageCircle} accent="amber" /><StatCard label="新增潜客" value={stats.leads || 50} helper={`${stats.s_leads || 15} 个 S 级机会`} icon={Target} accent="green" /></div><div className="content-grid"><section className="panel radar-panel"><div className="panel-header"><div><div className="section-kicker"><span className="live-line" />LIVE FEED</div><h3>实时截流雷达</h3></div><Badge tone="green">正在工作</Badge></div><div className="event-list">{events.length ? events.map((event: AnyRecord, index) => <div className="event-row" key={`${event.id || 'live'}-${index}`}><div className="event-time">{formatTime(event.created_at)}</div><div className={`event-dot ${event.event_type?.includes('lead') ? 'hot' : ''}`} /><div className="event-content"><div>{event.message}</div>{event.payload?.keyword && <span className="event-meta">关键词 · {event.payload.keyword}</span>}</div>{event.event_type === 'task.completed' && <Check size={16} className="event-check" />}</div>) : <Empty text="启动一次智能扫描，事件会实时出现在这里" />}</div><Link to="/tasks" className="panel-link">查看全部任务事件 <ArrowUpRight size={14} /></Link></section><section className="panel opportunity-panel"><div className="panel-header"><div><div className="section-kicker">TOP OPPORTUNITY</div><h3>高价值机会</h3></div><Link to="/leads" className="text-link">潜客池 <ArrowUpRight size={13} /></Link></div><div className="opportunity-list"><Opportunity name="长沙装修多少钱" score="97" leads="36" level="S" /><Opportunity name="旧房翻新避坑" score="92" leads="28" level="A" /><Opportunity name="120平装修预算" score="89" leads="21" level="A" /></div><div className="mini-insight"><BrainCircuit size={16} /><span>AI 洞察：<b>预算、增项、靠谱</b> 是近期评论里最强的购买信号。</span></div></section></div></>
}
function Opportunity({ name, score, leads, level }: AnyRecord) { return <div className="opportunity-row"><div className={`level level-${level.toLowerCase()}`}>{level}</div><div className="opp-name"><b>{name}</b><span>机会评分 {score}</span></div><div className="opp-leads"><b>{leads}</b><span>潜客</span></div><ChevronRight size={16} className="muted-icon" /></div> }
function Empty({ text }: { text: string }) { return <div className="empty"><Activity size={20} /><span>{text}</span></div> }
function formatTime(value?: string) { return value ? new Date(value).toLocaleTimeString('zh-CN', { hour12: false }) : '--:--:--' }

function SmartMode({ projectId, setProjectId, setProjects }: AnyRecord) {
  const [form, setForm] = useState({ name: '长沙装修新雷达', industry: '装修', location: '长沙', service: '旧房翻新 / 全屋装修', price_range: '5万-30万', target_customer: '准备装修的长沙业主', description: '专注本地旧房翻新和全屋装修，提供设计、施工与预算建议。' }); const [stage, setStage] = useState(''); const [result, setResult] = useState<AnyRecord>(); const [error, setError] = useState('')
  const update = (key: string, value: string) => setForm((old) => ({ ...old, [key]: value }))
  async function start() { setError(''); setStage('creating'); try { const project = await api('/api/projects', { method: 'POST', body: JSON.stringify(form) }); setProjectId(project.id); setProjects((old: AnyRecord[]) => [project, ...old]); setStage('analyzing'); const analysis = await api(`/api/projects/${project.id}/smart-mode`, { method: 'POST' }); setResult(analysis); setStage('starting'); await api(`/api/projects/${project.id}/scan`, { method: 'POST' }); setStage('done') } catch (err: any) { setError(err.message); setStage('') } }
  const stages = ['正在理解行业…', '正在分析客户语言…', '正在发现购买意图…', '正在生成搜索关键词…', '正在建立行业雷达…']
  return <><PageTitle eyebrow="INDUSTRY INTELLIGENCE" title="开启智能截流" description="告诉 AI 你做什么生意，其余交给系统。"><button className="button subtle"><Wifi size={15} /> Provider：Mock Demo</button></PageTitle><div className="smart-layout"><section className="panel form-panel"><div className="form-header"><div className="magic-icon"><Sparkles size={18} /></div><div><h3>描述你的业务</h3><p>信息越具体，AI 找到的客户越接近真实成交机会。</p></div></div><div className="form-grid"><Field label="行业" value={form.industry} onChange={(v: string) => update('industry', v)} placeholder="例如：装修、教育、财税" /><Field label="地区" value={form.location} onChange={(v: string) => update('location', v)} placeholder="例如：长沙" /><Field label="业务 / 产品服务" wide value={form.service} onChange={(v: string) => update('service', v)} placeholder="你具体提供什么服务？" /><Field label="客单价" value={form.price_range} onChange={(v: string) => update('price_range', v)} placeholder="例如：5万-30万" /><Field label="目标客户" wide value={form.target_customer} onChange={(v: string) => update('target_customer', v)} placeholder="谁最可能购买？" /><Field label="补充介绍" wide area value={form.description} onChange={(v: string) => update('description', v)} placeholder="补充你的优势、客户痛点、服务限制…" /></div>{error && <div className="error-note"><X size={15} />{error}</div>}<button className="button primary large-button" onClick={start} disabled={!!stage && stage !== 'done'}><Sparkles size={17} />{stage === 'done' ? '雷达已开启' : '分析行业并开启智能模式'}<ArrowUpRight size={15} /></button><div className="safety-note"><Check size={14} />仅处理公开内容；AI 建议需人工确认，不会自动发送营销消息。</div></section><section className="panel ai-preview"><div className="section-kicker">AI WORKFLOW</div><h3>从一句业务描述开始</h3><div className="workflow-steps">{stages.map((label, index) => <div className={`workflow-step ${stage ? index < (stage === 'done' ? 5 : 2) ? 'complete' : index === 2 ? 'current' : '' : ''}`} key={label}><div className="workflow-icon">{stage === 'done' || index < 2 ? <Check size={14} /> : index === 2 && stage ? <span className="spinner" /> : <span>{String(index + 1).padStart(2, '0')}</span>}</div><span>{stage === 'done' ? label.replace('…', '完成') : label}</span></div>)}</div>{result && <div className="analysis-result"><div className="result-number">{result.keyword_count}</div><div><b>AI 已生成行业关键词</b><span>机会词会优先扫描，低产出词自动降权</span></div><div className="category-chips">{Object.entries(result.categories || {}).slice(0, 6).map(([key, value]) => <span key={key}>{key} <b>{value as number}</b></span>)}</div></div>}{!result && <div className="preview-card"><div className="preview-glow" /><BrainCircuit size={30} /><b>行业理解尚未开始</b><span>右侧表单提交后，这里会展示 AI 的客户画像、痛点与搜索策略。</span></div>}</section></div></>
}
function Field({ label, value, onChange, placeholder, wide, area }: AnyRecord) { return <label className={`field ${wide ? 'wide' : ''}`}><span>{label}</span>{area ? <textarea value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} rows={3} /> : <input value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} />}</label> }

function Keywords({ projectId }: { projectId: number }) { const [items, setItems] = useState<AnyRecord[]>([]); useEffect(() => { api(`/api/projects/${projectId}/keywords`).then(setItems).catch(() => {}) }, [projectId]); return <><PageTitle eyebrow="OPPORTUNITY ENGINE" title="关键词雷达" description="AI 已按购买意图、商业价值和地域相关度，为你的行业排序。"><button className="button primary"><Sparkles size={15} />重新生成</button></PageTitle><div className="summary-strip"><div><b>{items.length || 50}</b><span>行业关键词</span></div><div><b>{items.filter((i) => i.opportunity_score >= 85).length || 18}</b><span>高机会词</span></div><div><b>30%</b><span>购买意图权重</span></div><div className="strip-note"><BrainCircuit size={16} />优先扫描高机会词，历史产出会动态影响排序</div></div><section className="panel table-panel"><div className="table-toolbar"><div className="filter-tabs"><button className="selected">全部 <span>{items.length || 50}</span></button><button>购买意向</button><button>痛点词</button><button>地域词</button><button>长尾词</button></div><div className="table-search"><Search size={15} />搜索关键词</div></div><table><thead><tr><th>关键词</th><th>类型</th><th>商业价值</th><th>机会评分</th><th>视频</th><th>评论</th><th>潜客</th><th>最近扫描</th><th>状态</th></tr></thead><tbody>{(items.length ? items : demoKeywords).slice(0, 14).map((item: AnyRecord, i) => <tr key={item.id || i}><td><b>{item.keyword}</b><small>{item.reason || 'AI 推荐 · 需求明确'}</small></td><td><Badge tone={item.category === '购买意向' ? 'purple' : 'neutral'}>{item.category || '需求词'}</Badge></td><td><div className="meter"><i style={{ width: `${item.commercial_score || 82}%` }} /></div><span className="meter-value">{item.commercial_score || 82}</span></td><td><span className={`score ${Number(item.opportunity_score || 90) > 90 ? 'hot-score' : ''}`}>{Math.round(item.opportunity_score || 90)}</span></td><td>{item.video_count || Math.max(2, i)}</td><td>{item.comment_count || Math.max(18, i * 8)}</td><td><b className="green-text">{item.lead_count || [36, 28, 21, 18][i % 4]}</b></td><td className="muted-text">{item.last_scanned_at ? formatTime(item.last_scanned_at) : '刚刚'}</td><td><span className="status-dot"><i />已启用</span></td></tr>)}</tbody></table></section></> }
const demoKeywords = ['长沙装修多少钱', '长沙装修哪家好', '旧房翻新避坑', '120平装修预算', '有没有靠谱装修公司', '装修增项怎么办', '长沙全屋定制', '准备装修怎么选公司', '望城装修公司', '装修报价贵不贵', '100平硬装预算', '长沙老房改造', '装修公司推荐', '装修合同注意事项'].map((keyword, i) => ({ keyword, category: ['购买意向', '问题词', '避坑词', '价格词'][i % 4], opportunity_score: 97 - i, commercial_score: 84 + (i % 15), lead_count: 36 - i }));

function Videos({ projectId }: { projectId: number }) { const [items, setItems] = useState<AnyRecord[]>([]); useEffect(() => { api(`/api/videos?project_id=${projectId}`).then(setItems).catch(() => {}) }, [projectId]); return <><PageTitle eyebrow="CONTENT RADAR" title="热门视频" description="不是只看点赞，而是看哪个视频的评论区更接近真实需求。"><div className="view-toggle"><button className="selected">列表</button><button>看板</button></div></PageTitle><section className="video-grid">{(items.length ? items : Array.from({ length: 8 }, (_, i) => ({ id: i, title: ['长沙装修最容易踩的 8 个坑', '120 平米装修预算怎么分配？', '旧房翻新前一定要看这条'][i % 3], creator: `长沙装修观察员${i + 1}`, likes: 1200 + i * 800, comments: 80 + i * 17, opportunity_score: 96 - i * 2, level: i < 3 ? 'A' : 'B', keyword: '长沙装修避坑' }))).map((video: AnyRecord, i) => <div className="video-card" key={video.id || i}><div className="video-cover"><div className="cover-label">DOUYIN</div><div className="cover-title">装修<br /><em>避坑指南</em></div><div className="play-button">▶</div></div><div className="video-body"><div className="video-title">{video.title}</div><div className="video-creator"><div className="creator-avatar">{(video.creator || '长')[0]}</div>{video.creator} <span>·</span> {video.keyword}</div><div className="video-metrics"><span>♡ {video.likes?.toLocaleString()}</span><span>◌ {video.comments}</span><strong>{Math.round(video.opportunity_score || 90)}</strong><Badge tone={video.level === 'A' ? 'purple' : 'neutral'}>{video.level || 'B'} 级</Badge></div></div></div>)}</section></> }

function Leads({ projectId }: { projectId: number }) { const [items, setItems] = useState<AnyRecord[]>([]); useEffect(() => { api(`/api/leads?project_id=${projectId}`).then(setItems).catch(() => {}) }, [projectId]); return <><PageTitle eyebrow="CUSTOMER SIGNALS" title="潜客池" description="从公开评论里识别购买意图，合并重复出现，并按优先级交给你人工跟进。"><Link to="/smart-mode" className="button primary"><Sparkles size={15} />继续扫描</Link></PageTitle><div className="lead-tabs"><button className="active">全部 <b>{items.length || 50}</b></button><button>S 级 <b>{items.filter((i) => i.lead_level === 'S').length || 15}</b></button><button>A 级 <b>{items.filter((i) => i.lead_level === 'A').length || 20}</b></button><button>待跟进 <b>{items.filter((i) => i.status === 'NEW').length || 50}</b></button><button>已联系</button><div className="lead-filter"><Search size={15} />筛选潜客</div></div><section className="panel lead-table"><div className="table-toolbar"><span className="result-count"><span className="pulse-dot" />实时排序 · 评分最高优先</span><button className="button subtle">导出列表 <ArrowUpRight size={14} /></button></div><table><thead><tr><th>潜客</th><th>意向评分</th><th>需求</th><th>地区 / 预算</th><th>购买阶段</th><th>原评论</th><th>出现</th><th>状态</th></tr></thead><tbody>{(items.length ? items : demoLeads).slice(0, 14).map((lead: AnyRecord, i) => <tr key={lead.id || i} onClick={() => lead.id && (window.location.href = `/leads/${lead.id}`)}><td><div className="lead-person"><div className={`lead-avatar avatar-${i % 4}`}>{(lead.nickname || '装')[0]}</div><div><b>{lead.nickname}</b><small>抖音 · {lead.platform_user_id || 'buyer-00' + i}</small></div></div></td><td><span className={`lead-score score-${lead.lead_level?.toLowerCase() || 'a'}`}>{Math.round(lead.lead_score || 90)} <small>{lead.lead_level || 'A'}</small></span></td><td><b>{lead.need || '旧房翻新 / 全屋装修'}</b><small>{lead.pain_point || '关注预算与靠谱程度'}</small></td><td>{lead.location || '长沙'}<small>{lead.budget || '预算待确认'}</small></td><td><Badge tone="purple">{lead.purchase_stage || 'comparison'}</Badge></td><td className="comment-quote">“{lead.content || ['长沙有没有靠谱一点的？', '我家120平，15万能下来吗？', '旧房翻新大概多少钱？'][i % 3]}”</td><td><span className="occurrence">{lead.occurrence_count || 1} 次</span></td><td><Badge tone={lead.status === 'CONTACTED' ? 'blue' : 'green'}>{lead.status === 'CONTACTED' ? '已联系' : '待跟进'}</Badge></td></tr>)}</tbody></table></section></> }
const demoLeads = Array.from({ length: 14 }, (_, i) => ({ id: i + 1, nickname: ['装修小白', '想翻新的阿敏', '长沙业主老周', '望城小何', '小满准备装修', '被增项坑过'][i % 6], lead_score: [97, 96, 94, 92, 90, 88, 86][i % 7], lead_level: i < 5 ? 'S' : i < 10 ? 'A' : 'B', need: '旧房翻新 / 全屋装修', location: '长沙', budget: i % 3 ? '15万' : '待确认', purchase_stage: 'comparison', occurrence_count: i % 4 + 1 }));

function LeadDetail() { const { leadId } = useParams(); const [lead, setLead] = useState<AnyRecord>(); const [advice, setAdvice] = useState<AnyRecord>(); useEffect(() => { api(`/api/leads/${leadId}`).then(setLead).catch(() => {}) }, [leadId]); async function generate() { setAdvice(await api(`/api/leads/${leadId}/persona`, { method: 'POST' })) } if (!lead) return <div className="loading">正在读取客户画像…</div>; return <><Link to="/leads" className="back-link">← 返回潜客池</Link><PageTitle eyebrow="LEAD PROFILE" title={lead.nickname} description="公开评论线索 · 仅供人工判断与跟进"><Badge tone={lead.lead_level === 'S' ? 'red' : 'purple'}>{lead.lead_level} 级高价值潜客</Badge></PageTitle><div className="detail-grid"><section className="panel profile-card"><div className="profile-top"><div className="big-avatar">{lead.nickname?.[0] || '客'}</div><div><h3>{lead.nickname}</h3><span className="muted-text">抖音用户 · {lead.platform_user_id}</span></div><div className="big-score"><b>{Math.round(lead.lead_score)}</b><span>意向评分</span></div></div><div className="detail-stats"><div><span>需求</span><b>{lead.need || '旧房翻新 / 全屋装修'}</b></div><div><span>地区</span><b>{lead.location || '长沙'}</b></div><div><span>预算</span><b>{lead.budget || '待确认'}</b></div><div><span>购买阶段</span><b>{lead.purchase_stage || 'comparison'}</b></div></div><div className="detail-section"><div className="section-kicker">AI SUMMARY</div><p>{lead.summary || '客户正在认真了解装修方案，评论中出现了明确的需求和决策信号。'}</p></div><div className="signal-box"><div className="section-kicker">BUYING SIGNALS</div><div className="signal-list">{(lead.buying_signals || ['明确询价', '表达真实需求', '关注本地服务']).map((item: string) => <span key={item}><Check size={13} />{item}</span>)}</div></div></section><section className="panel advice-card"><div className="panel-header"><div><div className="section-kicker">PERSONA AGENT</div><h3>人设跟进建议</h3></div><Bot size={20} className="violet-icon" /></div>{advice ? <div className="advice-result"><div className="advice-label">推荐回复 · {advice.communication_strategy}</div><blockquote>{advice.recommended_reply}</blockquote><div className="follow-question"><b>可以继续问</b><span>{advice.follow_up_question}</span></div><div className="warning-list">{advice.warnings?.map((w: string) => <span key={w}>• {w}</span>)}</div></div> : <div className="advice-empty"><Bot size={28} /><b>让 AI 按人设写一条建议</b><span>不自动发送，只生成像朋友一样的专业回答。</span><button className="button primary" onClick={generate}><Sparkles size={15} />生成跟进建议</button></div>}<div className="detail-section comments-history"><div className="section-kicker">COMMENT HISTORY</div><div className="history-item"><div className="history-dot" /><div><p>“{lead.content || '长沙有没有靠谱一点的？'}”</p><span>首次发现 · 公开评论</span></div></div></div></section></div></> }

function Agents({ projectId }: { projectId: number }) { const agents: Array<{ name: string; title: string; desc: string; Icon: LucideIcon; status: string }> = [{ name: 'IndustryAgent', title: '行业理解', desc: '把你的业务描述转成客户画像、痛点和搜索策略。', Icon: BrainCircuit, status: '已就绪' }, { name: 'KeywordAgent', title: '关键词发现', desc: '生成 50 个跨意图关键词，并计算机会评分。', Icon: Search, status: '已运行' }, { name: 'LeadJudgeAgent', title: '潜客判断', desc: '先规则预筛，再用 AI 判断真实购买信号。', Icon: Target, status: '已运行' }, { name: 'PersonaAgent', title: '人设跟进', desc: '把客户上下文变成专业、克制的人工跟进建议。', Icon: MessageCircle, status: '待调用' }]; return <><PageTitle eyebrow="AGENT SYSTEM" title="智能体" description="四个专注单一职责的智能体，协作完成从行业理解到人工跟进建议。" /><div className="agent-grid">{agents.map(({ name, title, desc, Icon, status }) => <div className="panel agent-card" key={name}><div className="agent-icon"><Icon size={20} /></div><div className="agent-card-title"><h3>{title}</h3><Badge tone="green">{status}</Badge></div><div className="agent-name">{name} · v1</div><p>{desc}</p><div className="agent-footer"><span><Activity size={13} /> Mock LLM fallback</span><ChevronRight size={15} /></div></div>)}</div><div className="panel prompt-panel"><div><div className="section-kicker">PROMPT REGISTRY</div><h3>可追踪的提示词版本</h3><p>每次 Agent 调用都会记录 prompt version、输入哈希、延迟和输出，方便后续评估效果。</p></div><Badge tone="purple">4 个版本已记录</Badge></div></> }

function Tasks({ projectId }: { projectId: number }) { const [items, setItems] = useState<AnyRecord[]>([]); useEffect(() => { api(`/api/tasks?project_id=${projectId}`).then(setItems).catch(() => {}) }, [projectId]); return <><PageTitle eyebrow="ORCHESTRATION" title="任务中心" description="每个扫描都是可暂停、可恢复、可重试的任务。"><Link to="/smart-mode" className="button primary"><Sparkles size={15} />新建扫描</Link></PageTitle><div className="task-layout"><section className="panel task-list"><div className="panel-header"><h3>扫描任务</h3><Badge tone="green">{items.length || 1} 个任务</Badge></div>{(items.length ? items : [{ id: 'demo', name: '长沙装修行业扫描', status: 'completed', current_step: 'update_dashboard', created_at: new Date().toISOString() }]).map((task: AnyRecord) => <div className="task-row" key={task.id}><div className="task-status-icon"><Check size={15} /></div><div><b>{task.name}</b><span>10 步 · {task.current_step || '等待中'}</span></div><Badge tone={task.status === 'completed' ? 'green' : 'amber'}>{task.status === 'completed' ? '已完成' : task.status}</Badge><ChevronRight size={16} className="muted-icon" /></div>)}</section><section className="panel checkpoint-card"><div className="section-kicker">RECOVERY STATE</div><h3>断点续跑</h3><p>每个关键词、视频和评论游标都会持久化。程序中断后，从上次 checkpoint 继续。</p><div className="checkpoint-visual"><div><span>last_keyword_id</span><b>50</b></div><div><span>processed_comment_ids</span><b>300</b></div><div><span>last_comment_cursor</span><b>unknown</b></div></div></section></div></> }
function Analytics({ projectId }: { projectId: number }) { const [data, setData] = useState<AnyRecord>({ levels: {} }); useEffect(() => { api(`/api/analytics?project_id=${projectId}`).then(setData).catch(() => {}) }, [projectId]); const chart = Object.entries(data.levels || {}).map(([name, value]) => ({ name, value })); return <><PageTitle eyebrow="SIGNAL ANALYTICS" title="数据分析" description="看见哪些行业语言正在产生真实的客户机会。" /><div className="analytics-grid"><section className="panel chart-panel"><div className="panel-header"><div><div className="section-kicker">LEAD QUALITY</div><h3>潜客等级分布</h3></div><span className="muted-text">当前项目</span></div><div className="donut-wrap"><ResponsiveContainer width="55%" height={220}><PieChart><Pie data={chart.length ? chart : [{ name: 'S', value: 15 }, { name: 'A', value: 20 }, { name: 'B', value: 15 }]} innerRadius={66} outerRadius={94} dataKey="value" strokeWidth={0}>{chart.map((entry: AnyRecord, i: number) => <Cell key={entry.name} fill={['#8166ff', '#a99aff', '#c9c1f6', '#e8e5f4'][i]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer><div className="chart-legend">{(chart.length ? chart : [{ name: 'S', value: 15 }, { name: 'A', value: 20 }, { name: 'B', value: 15 }]).map((item: AnyRecord) => <div key={item.name}><i className={`legend-dot ${item.name.toLowerCase()}`} /><span>{item.name} 级</span><b>{item.value}</b></div>)}</div></div></section><section className="panel chart-panel"><div className="section-kicker">RADAR HEALTH</div><h3>系统健康度</h3><div className="health-score">98<span>/100</span></div><div className="health-bars"><div><span>关键词覆盖</span><i><b style={{ width: '92%' }} /></i><b>92%</b></div><div><span>评论覆盖</span><i><b style={{ width: '78%' }} /></i><b>78%</b></div><div><span>AI 判断成功率</span><i><b style={{ width: '99%' }} /></i><b>99%</b></div></div></section></div></> }

function Providers() { const [items, setItems] = useState<AnyRecord[]>([]); useEffect(() => { api('/api/providers').then(setItems).catch(() => {}) }, []); async function check(item: AnyRecord) { await api(`/api/providers/${item.id}/health`, { method: 'POST' }); setItems(await api('/api/providers')) } return <><PageTitle eyebrow="PROVIDER LAYER" title="数据源管理" description="采集工具是可替换的 Provider，不会绑死 AI、CRM 与任务系统。" /><div className="provider-grid">{(items.length ? items : [{ name: 'Mock Provider', status: 'connected', note: 'Demo 数据源已就绪', capabilities: { keyword_search: true, comments: true } }, { name: 'Douyin Comments Crawler', status: 'disconnected', note: '外部 HTTP 服务未启动', endpoint: 'http://127.0.0.1:8000' }, { name: 'MediaCrawler (external)', status: 'disconnected', note: '仅允许调用独立外部安装实例' }, { name: 'Social Harvest (external)', status: 'disconnected', note: '等待 task report 路径' }]).map((item: AnyRecord, i) => <div className="panel provider-card" key={item.id || i}><div className="provider-head"><div className={`provider-logo provider-${i}`}><Database size={19} /></div><Badge tone={item.status === 'connected' ? 'green' : 'neutral'}>{item.status === 'connected' ? 'Connected' : item.status === 'disconnected' ? 'Disconnected' : item.status}</Badge></div><h3>{item.name}</h3><p>{item.note}</p>{item.endpoint && <code>{item.endpoint}</code>}<div className="capability-list">{Object.entries(item.capabilities || {}).slice(0, 4).map(([key, value]) => <span key={key} className={value ? 'on' : ''}><i />{key.replace('_', ' ')}</span>)}</div><button className="button subtle full" onClick={() => item.id && check(item)}><Wifi size={14} />检测服务</button></div>)}</div><div className="compliance-note"><Check size={16} /><span><b>合规边界：</b>外部 Provider 由用户独立运行并自行确认许可证与平台规则。系统不实现验证码破解、绕过风控或自动营销发送。</span></div></> }
function SettingsPage() { return <><PageTitle eyebrow="WORKSPACE SETTINGS" title="系统设置" description="管理 AI、扫描频率与工作区偏好。" /><div className="settings-list"><div className="panel setting-row"><div><h3>AI Provider</h3><p>未配置 API Key 时使用本地 Mock fallback，仍可演示完整链路。</p></div><Badge tone="green">Mock fallback</Badge></div><div className="panel setting-row"><div><h3>扫描频率</h3><p>S 级视频高频、A 级中频、B 级低频；当前 Demo 使用手动开启。</p></div><select className="small-select"><option>每 3 小时</option><option>每 1 小时</option><option>每天</option></select></div><div className="panel setting-row"><div><h3>人工跟进保护</h3><p>所有 PersonaAgent 输出都只是建议，不会自动发送、加微信或触达客户。</p></div><Badge tone="blue">已启用</Badge></div></div></> }

export default App
